name: quizu_okuoul_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  http: ^0.13.5
  #internet_connection_checker: ^1.0.0+1
  internet_connection_checker: ^0.0.1+3
  #internet_connection_checker_plus: ^1.0.1
  data_connection_checker_tv: ^0.3.5-nullsafety

  simple_connection_checker: ^0.2.1



  shared_preferences: ^2.0.15
  phone_number: ^1.0.0
  pin_code_fields: ^7.4.0
  intl: ^0.17.0



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
